# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x]

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - name: Login to Github Npm Registry
              uses: healthplace/npmrc-registry-login-action@v1.0
              with:
                  scope: '@brownhounds'
                  registry: 'https://npm.pkg.github.com'
                  auth-token: ${{secrets.npm_token}}

            - name: '@monorepo - Install Dependencies'
              run: npm ci

            - name: '@brownhounds/wc-testing - Build'
              run: npm run build-testing

            - name: '@monorepo - Eslint'
              run: npm run lint

            - name: '@brownhounds/wc-micro - Test'
              run: npm run test-micro

            - name: '@brownhounds/wc-micro - Build'
              run: npm run build-micro
